# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_account_order_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:indexAction
        _sylius:
            template: SyliusShopBundle:Account/Order:index.html.twig
            grid: sylius_shop_account_order
