twig_hooks:
    hooks:
        'sylius_shop.contact.index':
            header:
                template: '@SyliusShop/contact/index/header.html.twig'
            form:
                template: '@SyliusShop/contact/index/form.html.twig'
                
        'sylius_shop.contact.index.form':
            email:
                template: '@SyliusShop/contact/index/form/email.html.twig'
            message:
                template: '@SyliusShop/contact/index/form/message.html.twig'
            submit:
                template: '@SyliusShop/contact/index/form/submit.html.twig'
