sylius_shop_homepage:
    path: /
    defaults:
        _controller: sylius.controller.shop.homepage:indexAction

sylius_shop_product:
    resource: "@SyliusShopBundle/Resources/config/routing/product.yml"
