# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_grid:
    grids:
        sylius_shop_account_order:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.order.class%"
                    repository:
                        method: createByCustomerIdQueryBuilder
                        arguments: [expr:service('sylius.context.customer').getCustomer().getId()]
            sorting:
                checkoutCompletedAt: desc
            fields:
                number:
                    type: twig
                    label: sylius.ui.number
                    sortable: ~
                    options:
                        template: SyliusShopBundle:Account/Order/Grid/Field:number.html.twig
                checkoutCompletedAt:
                    type: datetime
                    label: sylius.ui.date
                    sortable: ~
                    options:
                        format: m/d/Y
                shippingAddress:
                    type: twig
                    label: sylius.ui.ship_to
                    options:
                        template: SyliusShopBundle:Account/Order/Grid/Field:shippingAddress.html.twig
                total:
                    type: twig
                    label: sylius.ui.total
                    path: .
                    sortable: total
                    options:
                        template: SyliusShopBundle:Account/Order/Grid/Field:total.html.twig
                state:
                    type: twig
                    label: sylius.ui.state
                    sortable: ~
                    options:
                        template: SyliusShopBundle:Account/Order/Grid/Field:state.html.twig
            actions:
                item:
                    show:
                        type: show
                        options:
                            link:
                                parameters:
                                    number: resource.number
                    pay:
                        type: pay_for_order
