# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_ajax_account_address_book_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.address:indexAction
        _format: json
        _sylius:
            section: shop_account
            paginate: false
            repository:
                method: findByCustomer
                arguments:
                    - 'expr:service("sylius.context.customer").getCustomer()'
