# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_shop_ajax_user_check_action:
    path: /check
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop_user::showAction
        _format: json
        _sylius:
            repository:
                method: findOneByEmail
                arguments:
                    email: $email
            serialization_groups: [Secured]
