# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "@SyliusUiBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusShopBundle/Resources/config/app/sylius/sylius_mailer.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/grids/account/order.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/grids/product.yml" }

sylius_grid:
    templates:
        action:
            pay: "@SyliusShop/Account/Order/Grid/Action/_pay_deprecated.html.twig"
            shop_show: "@SyliusShop/Grid/Action/show.html.twig"
            shop_pay: "@SyliusShop/Account/Order/Grid/Action/pay.html.twig"
        filter:
            shop_string: "@SyliusShop/Grid/Filter/string.html.twig"

sylius_shop:
    checkout_resolver:
        pattern: /checkout/.+
        route_map:
            empty_order:
                route: sylius_shop_cart_summary
            cart:
                route: sylius_shop_checkout_address
            addressed:
                route: sylius_shop_checkout_select_shipping
            shipping_selected:
                route: sylius_shop_checkout_select_payment
            shipping_skipped:
                route: sylius_shop_checkout_select_payment
            payment_selected:
                route: sylius_shop_checkout_complete
            payment_skipped:
                route: sylius_shop_checkout_complete

liip_imagine:
    filter_sets:
        sylius_shop_product_original: ~
        sylius_shop_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        sylius_shop_product_small_thumbnail:
            filters:
                thumbnail: { size: [150, 112], mode: outbound }
        sylius_shop_product_thumbnail:
            filters:
                thumbnail: { size: [260, 260], mode: outbound }
        sylius_shop_product_large_thumbnail:
            filters:
                thumbnail: { size: [550, 412], mode: outbound }

sonata_block:
    default_contexts: ~

sylius_ui:
    events:
        sylius.shop.layout.after_body:
            blocks:
                after_body_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.after_body

        sylius.shop.layout.after_content:
            blocks:
                after_content_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.after_content

        sylius.shop.layout.before_body:
            blocks:
                before_body_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.before_body

        sylius.shop.layout.before_content:
            blocks:
                before_content_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.before_content

        sylius.shop.layout.footer:
            blocks:
                before_footer_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.shop.layout.before_footer
                content:
                    template: "@SyliusShop/Block/Layout/_footerContent.html.twig"
                    priority: 10
                after_footer_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.layout.after_footer

        sylius.shop.layout.head:
            blocks:
                head_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.head

        sylius.shop.layout.header:
            blocks:
                header:
                    template: "@SyliusShop/Block/Layout/_header.html.twig"
                    priority: 10
                after_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.layout.after_header

        sylius.shop.layout.header_content:
            blocks:
                header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.layout.header

        sylius.shop.layout.javascripts:
            blocks:
                javascripts_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.javascripts

        sylius.shop.layout.stylesheets:
            blocks:
                internet_explorer_additions:
                    template: "@SyliusShop/Block/Layout/_internetExplorerAdditions.html.twig"
                    priority: 20
                stylesheets:
                    template: "@SyliusShop/Block/Layout/_stylesheets.html.twig"
                    priority: 10
                stylesheets_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.layout.stylesheets

        sylius.shop.layout.topbar:
            blocks:
                before_switchers_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 35
                    context:
                        event: sylius.shop.layout.before_currency_switcher
                currency_switcher:
                    template: "@SyliusShop/Block/Layout/_currencySwitcher.html.twig"
                    priority: 30
                locale_switcher:
                    template: "@SyliusShop/Block/Layout/_localeSwitcher.html.twig"
                    priority: 20
                before_security_widget_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.shop.layout.before_security_widget
                security_widget:
                    template: "@SyliusShop/Block/Layout/_securityWidget.html.twig"
                    priority: 10
                after_security_widget_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.layout.after_security_widget

        sylius.shop.homepage:
            blocks:
                banner:
                    template: "@SyliusShop/Homepage/Block/_banner.html.twig"
                    priority: 60
                latest_products:
                    template: "@SyliusShop/Homepage/Block/_latestProducts.html.twig"
                    priority: 50
                latest_products_carousel:
                    template: "@SyliusShop/Homepage/Block/_latestProductsCarousel.html.twig"
                    priority: 40
                newsletter:
                    template: "@SyliusShop/Homepage/Block/_newsletter.html.twig"
                    priority: 30
                products_grid:
                    template: "@SyliusShop/Homepage/Block/_productsGrid.html.twig"
                    priority: 20
                about_us:
                    template: "@SyliusShop/Homepage/Block/_aboutUs.html.twig"
                    priority: 10

        sylius.shop.cart.widget.button:
            blocks:
                before_widget_content_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.shop.partial.cart.summary.before_widget_content
                button:
                    template: "@SyliusShop/Cart/Block/_widgetButton.html.twig"
                    priority: 10
                after_widget_content_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.partial.cart.summary.after_widget_content

        sylius.shop.cart.widget.popup:
            blocks:
                before_popup_content_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.shop.partial.cart.summary.before_popup_content
                content:
                    template: "@SyliusShop/Cart/Block/_popupContent.html.twig"
                    priority: 10
                after_popup_content_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.partial.cart.summary.after_popup_content

        sylius.shop.cart.coupon:
            blocks:
                before_coupon_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.shop.cart.summary.before_coupon
                coupon:
                    template: "@SyliusShop/Cart/Block/_coupon.html.twig"
                    priority: 10
                after_coupon_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.cart.summary.after_coupon

        sylius.shop.cart.header:
            blocks:
                header:
                    template: "@SyliusShop/Cart/Block/_header.html.twig"
                    priority: 10
                after_content_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.cart.summary.after_content_header

        sylius.shop.cart.items:
            blocks:
                before_items_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 20
                    context:
                        event: sylius.shop.cart.summary.before_items
                items_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.shop.cart.summary.items
                items:
                    template: "@SyliusShop/Cart/Block/_items.html.twig"
                    priority: 10
                after_items_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.cart.summary.after_items

        sylius.shop.cart.suggestions:
            blocks:
                before_suggestions_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 10
                    context:
                        event: sylius.shop.cart.summary.before_suggestions
                suggestions:
                    template: "@SyliusShop/Cart/Block/_suggestions.html.twig"
                    priority: 5

        sylius.shop.cart.summary:
            blocks:
                before_totals_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.shop.cart.summary.before_totals
                totals:
                    template: "@SyliusShop/Cart/Block/_totals.html.twig"
                    priority: 20
                after_totals_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.shop.cart.summary.after_totals
                checkout:
                    template: "@SyliusShop/Cart/Block/_checkout.html.twig"
                    priority: 10

        sylius.shop.cart.summary.totals:
            blocks:
                totals_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.cart.summary.totals
