# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.
        
imports:
    - { resource: "@SyliusUiBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusShopBundle/Resources/config/app/sylius/sylius_mailer.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/grids/account/order.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/grids/product.yml" }

parameters:
    sylius.security.shop_regex: "^/(?!%sylius_admin.path_name%|api/.*|api$|media/.*)[^/]++"

twig:
    paths:
        '%kernel.project_dir%/src/Sylius/Bundle/ShopBundle/Resources/private/': 'SyliusShopAssets'
        
webpack_encore:
    builds:
        shop: '%kernel.project_dir%/public/build/shop'

sylius_grid:
    templates:
        action:
            shop_show: "@SyliusShop/Grid/Action/show.html.twig"
            shop_pay: "@SyliusShop/Account/order/grid/action/pay.html.twig"
        filter:
            shop_string: "@SyliusShop/Grid/Filter/string.html.twig"

sylius_shop:
    checkout_resolver:
        pattern: "%sylius.security.shop_regex%/checkout/.+"
        route_map:
            empty_order:
                route: sylius_shop_cart_summary
            cart:
                route: sylius_shop_checkout_address
            addressed:
                route: sylius_shop_checkout_select_shipping
            shipping_selected:
                route: sylius_shop_checkout_select_payment
            shipping_skipped:
                route: sylius_shop_checkout_select_payment
            payment_selected:
                route: sylius_shop_checkout_complete
            payment_skipped:
                route: sylius_shop_checkout_complete

liip_imagine:
    filter_sets:
        sylius_shop_product_original: ~
        sylius_shop_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        sylius_shop_product_small_thumbnail:
            filters:
                thumbnail: { size: [150, 112], mode: outbound }
        sylius_shop_product_thumbnail:
            filters:
                thumbnail: { size: [260, 260], mode: outbound }
        sylius_shop_product_large_thumbnail:
            filters:
                thumbnail: { size: [550, 412], mode: outbound }

sonata_block:
    default_contexts: ~

sylius_ui:
    events:
        sylius.shop.layout.topbar:
            blocks:
                topbar:
                    template: "@SyliusShop/Layout/_topBar.html.twig"
                    priority: 10
                    
        sylius.shop.layout.topbar.content:
            blocks:
                before_switchers_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 45
                    context:
                        event: sylius.shop.layout.before_currency_switcher
                info_message:
                    template: "@SyliusShop/Layout/TopBar/_infoMessage.html.twig"
                    priority: 40
                currency_switcher:
                    template: "@SyliusShop/Layout/TopBar/_currencySwitcher.html.twig"
                    priority: 30
                locale_switcher:
                    template: "@SyliusShop/Layout/TopBar/_localeSwitcher.html.twig"
                    priority: 20

        sylius.shop.homepage:
            blocks:
                banner:
                    template: "@SyliusShop/Homepage/banner.html.twig"
                    priority: 40
                latest_deals:
                    template: "@SyliusShop/Homepage/latest_deals.html.twig"
                    priority: 30
                new_collection:
                    template: "@SyliusShop/Homepage/new_collection.html.twig"
                    priority: 20
                latest_products:
                    template: "@SyliusShop/Homepage/latest_products.html.twig"
                    priority: 10

        sylius.shop.cart.widget.button:
            blocks:
                content:
                    template: "@SyliusShop/Cart/widget/button.html.twig"
                    priority: 10

        sylius.shop.cart.widget.popup:
            blocks:
                content:
                    template: "@SyliusShop/Cart/widget/popup.html.twig"
                    priority: 10

        sylius.shop.cart.header:
            blocks:
                header:
                    template: "@SyliusShop/Cart/header/header.html.twig"
                    priority: 10

        sylius.shop.cart.items:
            blocks:
                content:
                    template: "@SyliusShop/Cart/items/items.html.twig"
                    priority: 10

        sylius.shop.cart.footer:
            blocks:
                content:
                    template: "@SyliusShop/Cart/footer/suggestions.html.twig"
                    priority: 5

        sylius.shop.cart.summary:
            blocks:
                totals:
                    template: "@SyliusShop/Cart/summary/totals.html.twig"
                    priority: 20
                checkout:
                    template: "@SyliusShop/Cart/summary/checkout.html.twig"
                    priority: 10

        sylius.shop.account.profile.update.form:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.account.profile.update.form

        sylius.shop.contact.request.form:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.contact.request.form

        sylius.shop.account.layout.menu:
            blocks:
                menu:
                    template: "@SyliusShop/Account/menu/content.html.twig"
                    priority: 10
        
        sylius.shop.account.login:
            blocks:
                header:
                    template: "@SyliusShop/Account/login/header.html.twig"
                    priority: 40
                form:
                    template: "@SyliusShop/Account/login/form.html.twig"
                    priority: 30
                submit:
                    template: "@SyliusShop/Account/login/submit.html.twig"
                    priority: 20
                forgot_password:
                    template: "@SyliusShop/Account/login/forgot_password.html.twig"
                    priority: 10
                    
        sylius.shop.account.register:
            blocks:
                header:
                    template: "@SyliusShop/Account/register/header.html.twig"
                    priority: 40
                information:
                    template: "@SyliusShop/Account/register/information.html.twig"
                    priority: 30
                credentials:
                    template: "@SyliusShop/Account/register/credentials.html.twig"
                    priority: 20
                submit:
                    template: "@SyliusShop/Account/register/submit.html.twig"
                    priority: 10

        sylius.shop.account.order.show.after_content_header:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.account.order.show.after_content_header

        sylius.shop.contact.request.after_content_header:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.contact.request.after_content_header

        sylius.shop.product_review.index.sidebar:
            blocks:
                card:
                    template: "@SyliusShop/ProductReview/product_card.html.twig"
                    priority: 10

        sylius.shop.product_review.index.main:
            blocks:
                list:
                    template: "@SyliusShop/ProductReview/list.html.twig"
                    priority: 20
                actions:
                    template: "@SyliusShop/ProductReview/actions.html.twig"
                    priority: 10

        sylius.shop.product_review.create.sidebar:
            blocks:
                card:
                    template: "@SyliusShop/Product/card.html.twig"
                    priority: 10         

        sylius.shop.product_review.create.main:
            blocks:
                form:
                    template: "@SyliusShop/ProductReview/form.html.twig"
                    priority: 10

        sylius.shop.product.index.header:
            blocks:
                breadcrumbs:
                    template: "@SyliusShop/Product/index/header/breadcrumbs.html.twig"
                    priority: 10
                    
        sylius.shop.product.index.sidebar:
            blocks:
                content:
                    template: "@SyliusShop/Product/index/sidebar/taxonomy.html.twig"
                    priority: 10
                    
        sylius.shop.product.index.main:
            blocks:
                header:
                    template: "@SyliusShop/Product/index/main/header.html.twig"
                    priority: 50
                list:
                    template: "@SyliusShop/Product/index/main/list.html.twig"
                    priority: 20
                footer:
                    template: "@SyliusShop/Product/index/main/footer.html.twig"
                    priority: 10
            
        sylius.shop.order.thank_you.after_message:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.order.thank_you.after_message

        sylius.shop.checkout.header:
            blocks:
                header:
                    template: "@SyliusShop/Checkout/shared/header.html.twig"
                    priority: 10

        sylius.shop.layout.footer:
            blocks:
                content:
                    template: "@SyliusShop/Layout/_footer.html.twig"
                    priority: 10
                after_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.layout.after_footer

        sylius.shop.layout.header.grid:
            blocks:
                logo:
                    template: "@SyliusShop/Layout/Header/_logo.html.twig"
                    priority: 30
                security_widget:
                    template: "@SyliusShop/Layout/Header/_securityWidget.html.twig"
                    priority: 20
                cart:
                    template: "@SyliusShop/Layout/Header/_cart.html.twig"
                    priority: 10
                        
        sylius.shop.logo:
            blocks:
                logo:
                    template: "@SyliusShop/Shared/sylius_logo.html.twig"
                    priority: 10

        sylius.shop.layout.stylesheets:
            blocks:
                styles:
                    template: "@SyliusShop/_styles.html.twig"
                    priority: 10
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 0
                    context:
                        event: sylius.shop.layout.stylesheets

        sylius.shop.layout.javascripts:
            blocks:
                scripts:
                    template: "@SyliusShop/_scripts.html.twig"
                    priority: 10
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 0
                    context:
                        event: sylius.shop.layout.javascripts

        sylius.shop.layout.head:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.head

        sylius.shop.layout.before_content:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.before_content

        sylius.shop.layout.after_content:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.after_content

        sylius.shop.layout.header:
            blocks:
                header:
                    template: "@SyliusShop/Layout/_header.html.twig"
                    priority: 10
                        
        sylius.shop.layout.navbar:
            blocks:
                nav:
                    template: "@SyliusShop/Layout/Header/_menu.html.twig"
                    priority: 10

        sylius.shop.layout.before_body:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.before_body

        sylius.shop.layout.after_body:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.shop.layout.after_body

        sylius.shop.account.order.index.content:
            blocks:            
                content:
                    template: "@SyliusShop/Account/order/index/content.html.twig"
                    priority: 10

        sylius.shop.account.order.show.content:
            blocks:
                header:
                    template: "@SyliusShop/Account/order/show/header.html.twig"
                    priority: 20
                summary:
                    template: "@SyliusShop/Shared/order/summary.html.twig"
                    priority: 10

        sylius.shop.checkout.steps:
            blocks:
                steps:
                    template: "@SyliusShop/Checkout/shared/steps.html.twig"
                    priority: 10

        sylius.shop.checkout.address.steps:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 0
                    context:
                        event: sylius.shop.checkout.address.after_steps

        sylius.shop.checkout.sidebar:
            blocks:
                summary:
                    template: "@SyliusShop/Checkout/shared/summary.html.twig"
                    priority: 20

        sylius.shop.checkout.address.sidebar:
            blocks:
                before_summary_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.shop.checkout.address.before_summary
                before_support_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.shop.checkout.address.before_support
                after_support_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.shop.checkout.address.after_support

        sylius.shop.checkout.select_payment.sidebar:
            blocks:
                before_summary_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.shop.checkout.select_payment.before_summary
                before_support_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.shop.checkout.select_payment.before_support
                after_support_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.shop.checkout.select_payment.after_support

        sylius.shop.checkout.select_shipping.sidebar:
            blocks:
                before_summary_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.shop.checkout.select_shipping.before_summary
                before_support_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.shop.checkout.select_shipping.before_support
                after_support_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.checkout.select_shipping.after_support

        sylius.shop.checkout.complete.summary:
            blocks:
                content:
                    template: "@SyliusShop/Shared/order/summary.html.twig"
                    priority: 10

        sylius.shop.product.show.header:
            blocks:
                breadcrumb:
                    template: "@SyliusShop/Product/show/header/breadcrumbs.html.twig"
                    priority: 10
                    
        sylius.shop.product.show.summary:
            blocks:
                header:
                    template: "@SyliusShop/Product/show/summary/header.html.twig"
                    priority: 50
                price:
                    template: "@SyliusShop/Product/show/summary/price.html.twig"
                    priority: 40
                catalog_promotions:
                    template: "@SyliusShop/Product/show/summary/catalog_promotions.html.twig"
                    priority: 30
                variant_selection:
                    template: "@SyliusShop/Product/show/summary/variant_selection.html.twig"
                    priority: 20
                short_description:
                    template: "@SyliusShop/Product/show/summary/short_description.html.twig"
                    priority: 10

        sylius.shop.product.show.main:
            blocks:
                images:
                    template: "@SyliusShop/Product/show/main/images.html.twig"
                    priority: 30
                tabs:
                    template: "@SyliusShop/Product/show/main/accordion.html.twig"
                    priority: 20
                    
        sylius.shop.product.show.accordion:
            blocks:
                details:
                    template: "@SyliusShop/Product/show/accordion/details.html.twig"
                    priority: 30
                attributes:
                    template: "@SyliusShop/Product/show/accordion/attributes.html.twig"
                    priority: 20
                reviews:
                    template: "@SyliusShop/Product/show/accordion/reviews.html.twig"
                    priority: 10                    
                
        sylius.shop.product.show.footer:
            blocks:
                associations:
                    template: "@SyliusShop/Product/show/footer/associations.html.twig"
                    priority: 10
