twig_hooks:
    hooks:
        'sylius_shop.checkout.address':
            steps:
                template: '@SyliusShop/checkout/shared/steps.html.twig'
            form:
                template: '@SyliusShop/checkout/address/form.html.twig'

        'sylius_shop.checkout.address.form':
            header:
                template: '@SyliusShop/checkout/address/form/header.html.twig'
            addresses:
                template: '@SyliusShop/checkout/address/form/addresses.html.twig'
            navigation:
                template: '@SyliusShop/checkout/address/form/navigation.html.twig'
