twig_hooks:
    hooks:
        'sylius_shop.account.reset_password':
            header:
                template: '@SyliusShop/account/reset_password/header.html.twig'
            form:
                template: '@SyliusShop/account/reset_password/form.html.twig'

        'sylius_shop.account.reset_password.header':
            title:
                template: '@SyliusShop/account/reset_password/header/title.html.twig'
            subtitle:
                template: '@SyliusShop/account/reset_password/header/subtitle.html.twig'

        'sylius_shop.account.reset_password.form':
            fields:
                template: '@SyliusShop/account/reset_password/form/fields.html.twig'
            submit:
                template: '@SyliusShop/account/reset_password/form/submit.html.twig'

        'sylius_shop.account.reset_password.form.fields':
            new_password:
                template: '@SyliusShop/account/reset_password/form/fields/new_password.html.twig'
            new_password_confirmation:
                template: '@SyliusShop/account/reset_password/form/fields/new_password_confirmation.html.twig'
