twig_hooks:
    hooks:
        'sylius_shop.account.reset_password':
            form_start:
                template: '@SyliusShop/account/reset_password/form_start.html.twig'
            content:
                template: '@SyliusShop/account/reset_password/content.html.twig'
            form_end:
                template: '@SyliusShop/account/reset_password/form_end.html.twig'

        'sylius_shop.account.reset_password.content':
            header:
                template: '@SyliusShop/account/reset_password/content/header.html.twig'
            form:
                template: '@SyliusShop/account/reset_password/content/form.html.twig'

        'sylius_shop.account.reset_password.content.header':
            title:
                template: '@SyliusShop/account/reset_password/content/header/title.html.twig'
            subtitle:
                template: '@SyliusShop/account/reset_password/content/header/subtitle.html.twig'

        'sylius_shop.account.reset_password.content.form':
            fields:
                template: '@SyliusShop/account/reset_password/content/form/fields.html.twig'
            submit:
                template: '@SyliusShop/account/reset_password/content/form/submit.html.twig'

        'sylius_shop.account.reset_password.content.form.fields':
            new_password:
                template: '@SyliusShop/account/reset_password/content/form/fields/new_password.html.twig'
            new_password_confirmation:
                template: '@SyliusShop/account/reset_password/content/form/fields/new_password_confirmation.html.twig'
