twig_hooks:
    hooks:
        'sylius_shop.cart.page':
            form:
                component: 'sylius_shop:cart:form'
                props:
                    cart: '@=_context.cart'
            suggested_products:
                component: 'sylius_shop:homepage:latest_products'
                props:
                    limit: 4
                configuration:
                    title: 'sylius.ui.you_may_also_like'
                    
        'sylius_shop.cart.page.header':
            flashes:
                enabled: false

        'sylius_shop.cart.page.form':
            sections:
                template: '@SyliusShop/cart/page/form/sections.html.twig'

        'sylius_shop.cart.page.form.sections':
            flashes:
                template: "@SyliusShop/shared/flashes.html.twig"
            header:
                template: '@SyliusShop/cart/page/form/sections/header.html.twig'
            general:
                template: '@SyliusShop/cart/page/form/sections/general.html.twig'

        'sylius_shop.cart.page.form.sections.general#left':
            items:
                template: '@SyliusShop/cart/page/form/sections/general/items.html.twig'
            coupon:
                template: '@SyliusShop/cart/page/form/sections/general/coupon.html.twig'
            clear_cart:
                template: '@SyliusShop/cart/page/form/sections/general/clear_cart.html.twig'
        
        'sylius_shop.cart.page.form.sections.general.items':
            head:
                template: '@SyliusShop/cart/page/form/sections/general/items/head.html.twig'
            body:
                template: '@SyliusShop/cart/page/form/sections/general/items/body.html.twig'

        'sylius_shop.cart.page.form.sections.general.items.head':
            remove:
                template: '@SyliusShop/cart/page/form/sections/general/items/head/remove.html.twig'
            item:
                template: '@SyliusShop/cart/page/form/sections/general/items/head/item.html.twig'
            unit_price:
                template: '@SyliusShop/cart/page/form/sections/general/items/head/unit_price.html.twig'
            quantity:
                template: '@SyliusShop/cart/page/form/sections/general/items/head/quantity.html.twig'
            total:
                template: '@SyliusShop/cart/page/form/sections/general/items/head/total.html.twig'

        'sylius_shop.cart.page.form.sections.general.items.body':
            remove:
                template: '@SyliusShop/cart/page/form/sections/general/items/body/remove.html.twig'
            item:
                template: '@SyliusShop/cart/page/form/sections/general/items/body/item.html.twig'
            unit_price:
                template: '@SyliusShop/cart/page/form/sections/general/items/body/unit_price.html.twig'
            quantity:
                template: '@SyliusShop/cart/page/form/sections/general/items/body/quantity.html.twig'
            total:
                template: '@SyliusShop/cart/page/form/sections/general/items/body/total.html.twig'

        'sylius_shop.cart.page.form.sections.general#right':
            summary:
                component: 'sylius_shop:checkout:summary'
                props:
                    cart: '@=_context.cart'
            checkout:
                template: '@SyliusShop/cart/page/form/sections/general/checkout.html.twig'

        'sylius_shop.cart.page.form.sections.general.summary':
            items_total:
                template: '@SyliusShop/checkout/summary/items_total.html.twig'
            discount:
                template: '@SyliusShop/checkout/summary/discount.html.twig'
            estimated_cost:
                template: '@SyliusShop/checkout/summary/estimated_cost.html.twig'
            taxes_total:
                template: '@SyliusShop/checkout/summary/taxes_total.html.twig'
            order_total:
                template: '@SyliusShop/checkout/summary/order_total.html.twig'
            base_currency_order_total:
                template: '@SyliusShop/checkout/summary/base_currency_order_total.html.twig'
