twig_hooks:
    hooks:
        'sylius_shop.base#stylesheets':
            styles:
                template: '@SyliusShop/shared/layout/base/styles.html.twig'

        'sylius_shop.base#javascripts':
            scripts:
                template: '@SyliusShop/shared/layout/base/scripts.html.twig'

        'sylius_shop.base.header':
            top_bar:
                template: '@SyliusShop/shared/layout/base/header/top_bar.html.twig'
            content:
                template: '@SyliusShop/shared/layout/base/header/content.html.twig'
            navbar:
                template: '@SyliusShop/shared/layout/base/header/navbar.html.twig'
            flashes:
                template: '@SyliusShop/shared/layout/base/header/flashes.html.twig'

        'sylius_shop.base.header.top_bar':
            info_message:
                template: '@SyliusShop/shared/layout/base/header/top_bar/info_message.html.twig'
            currency_switcher:
                template: '@SyliusShop/shared/layout/base/header/top_bar/currency_switcher.html.twig'
            locale_switcher:
                template: '@SyliusShop/shared/layout/base/header/top_bar/locale_switcher.html.twig'

        'sylius_shop.base.header.content':
            logo:
                template: "@SyliusShop/shared/layout/base/header/content/logo.html.twig"
            security_widget:
                template: "@SyliusShop/shared/layout/base/header/content/security_widget.html.twig"
            cart:
                template: "@SyliusShop/shared/layout/base/header/content/cart.html.twig"

        'sylius_shop.base.header.content.logo':
            content:
                template: "@SyliusShop/shared/sylius_logo.html.twig"

        'sylius_shop.base.header.navbar':
            menu:
                template: "@SyliusShop/shared/layout/base/header/navbar/menu.html.twig"

        'sylius_shop.base.header.flashes':
            content:
                template: "@SyliusShop/shared/flashes.html.twig"

        'sylius_shop.base.footer':
            content:
                template: '@SyliusShop/shared/layout/base/footer/content.html.twig'

        'sylius_shop.base.footer.content':
            menu:
                template: '@SyliusShop/shared/layout/base/footer/content/menu.html.twig'
            payment_methods:
                template: '@SyliusShop/shared/layout/base/footer/content/payment_methods.html.twig'
            copy:
                template: '@SyliusShop/shared/layout/base/footer/content/copy.html.twig'
