# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_account_dashboard:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer:showProfileAction
        _sylius:
            template: SyliusShopBundle:Account:dashboard.html.twig

sylius_shop_account_profile_update:
    path: /profile/edit
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:updateAction
        _sylius:
            template: SyliusShopBundle:Account:updateProfile.html.twig
            form: sylius_customer_profile
            repository:
                method: find
                arguments: [expr:service('sylius.context.customer').getCustomer().getId()]
            redirect: sylius_shop_account_dashboard

sylius_shop_account_change_password:
    path: /change-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:changePasswordAction
        _sylius:
            template: SyliusShopBundle:Account:changePassword.html.twig
            redirect: sylius_shop_account_dashboard
