# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_account_dashboard:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer:showProfileAction
        _sylius:
            template: SyliusShopBundle:Account:dashboard.html.twig

sylius_shop_account_profile_update:
    path: /profile/edit
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:updateAction
        _sylius:
            template: SyliusShopBundle:Account:updateProfile.html.twig
            form: sylius_customer_profile
            repository:
                method: find
                arguments: [expr:service('sylius.context.customer').getCustomer().getId()]
            redirect: sylius_shop_account_dashboard

sylius_shop_account_registration:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            form: sylius_customer_registration
            event: register
            template: SyliusShopBundle:Account:register.html.twig
            permission: false
            redirect:
                route: sylius_shop_homepage
                parameters: { email: resource.email }
