# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_cart_summary:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:summaryAction
        _sylius:
            template: "@SyliusShop/Cart/summary.html.twig"

sylius_shop_cart_save:
    path: /
    methods: [PUT, PATCH]
    defaults:
        _controller: sylius.controller.order:saveAction
        _sylius:
            template: "@SyliusShop/Cart/summary.html.twig"
            redirect: sylius_shop_cart_summary
            flash: sylius.cart.save

sylius_shop_cart_clear:
    path: /
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.order:clearAction
        _sylius:
            redirect: sylius_shop_cart_summary

sylius_shop_cart_item_remove:
    path: /{id}/remove
    defaults:
        _controller: sylius.controller.order_item:removeAction
        _sylius:
            redirect: sylius_shop_cart_summary
            flash: sylius.cart.remove_item

sylius_shop_cart_item_add:
    path: /add
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.order_item:addAction
        _sylius:
            factory:
                method: createForProduct
                arguments: [expr:service('sylius.repository.product').find($productId)]
            form:
                type: Sylius\Bundle\CoreBundle\Form\Type\Order\AddToCartType
                options:
                    product: expr:service('sylius.repository.product').find($productId)
            template: $template
            redirect:
                route: sylius_shop_cart_summary
                parameters: {}
            flash: sylius.cart.add_item
