sylius_shop_checkout_addressing:
    path: /addressing
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            template: SyliusShopBundle:Checkout:addressing.html.twig
            form: sylius_shop_checkout_addressing
            flash: false
            repository:
                method: find
                arguments: [expr:service('sylius.cart_provider').getCart()]
            state_machine:
                graph: sylius_order_checkout
                transition: address
            redirect: sylius_shop_cart_summary
