# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_order_pay:
    path: /{lastNewPaymentId}/pay
    methods: [GET]
    defaults:
        _controller: sylius.controller.payum:prepareCaptureAction
        _sylius:
            redirect:
                route: sylius_shop_order_after_pay

sylius_shop_order_after_pay:
    path: /after-pay
    methods: [GET]
    defaults:
        _controller: sylius.controller.payum:afterCaptureAction

sylius_shop_order_thank_you:
    path: /thank-you
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:thankYouAction
        _sylius:
            template: SyliusShopBundle:Checkout:thankYou.html.twig

sylius_shop_order_show_details:
    path: /{tokenValue}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            template: SyliusShopBundle:Checkout:orderDetails.html.twig
            grid: sylius_shop_account_order
            section: shop_account
            repository:
                method: findOneBy
                arguments:
                    [tokenValue: $tokenValue]
