# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_order_pay:
    path: /{orderId}/{orderTokenValue}/pay
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:payAction
        _sylius:
            redirect:
                route: sylius_shop_thank_you
                parameters:
                    orderId: $orderId
                    orderTokenValue: $orderTokenValue
            after_pay:
                route: sylius_shop_order_after_pay
                parameters:
                    orderId: $orderId
                    orderTokenValue: $orderTokenValue

sylius_shop_order_after_pay:
    path: /{orderId}/{orderTokenValue}/after-pay
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:afterPayAction
        _sylius:
            redirect:
                route: sylius_shop_thank_you
                parameters:
                    orderId: $orderId
                    orderTokenValue: $orderTokenValue

sylius_shop_order_payment_method_update:
    path: /{orderId}/{orderTokenValue}/change-payment-method
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            permission: false
            template: SyliusShopBundle:Order:payment.html.twig
            form: sylius_checkout_select_payment
            repository:
                method: find
                arguments: [$orderId]
            redirect:
                route: sylius_shop_thank_you
                parameters:
                    orderId: $orderId
                    orderTokenValue: $orderTokenValue

sylius_shop_thank_you:
    path: /{orderId}/{orderTokenValue}/thank-you
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:thankYouAction
        _sylius:
            template: SyliusShopBundle:Checkout:thankYou.html.twig
            after_failure:
                route: sylius_shop_homepage
