# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_order_pay:
    path: /{tokenValue}/pay
    methods: [GET]
    defaults:
        _controller: sylius.controller.payum:prepareCaptureAction
        _sylius:
            redirect:
                route: sylius_shop_order_after_pay

sylius_shop_order_after_pay:
    path: /after-pay
    methods: [GET]
    defaults:
        _controller: sylius.controller.payum:afterCaptureAction

sylius_shop_order_thank_you:
    path: /thank-you
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:thankYouAction
        _sylius:
            template: "@SyliusShop/Order/thankYou.html.twig"

sylius_shop_order_change_payment_method:
    path: /{tokenValue}/change-payment-method
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            template: "@SyliusShop/Order/changePaymentMethod.html.twig"
            repository:
                method: findOneBy
                arguments: [tokenValue: $tokenValue]
            form: sylius_checkout_select_payment
            redirect:
                route: sylius_shop_order_pay
                parameters:
                    tokenValue: $tokenValue
            flash: false
