sylius_shop_partial_product:
    resource: "@SyliusShopBundle/Resources/config/routing/partial/product.yml"
    prefix: /products

sylius_shop_partial_taxon:
    resource: "@SyliusShopBundle/Resources/config/routing/partial/taxon.yml"
    prefix: /taxons

sylius_shop_partial_product:
    resource: "@SyliusShopBundle/Resources/config/routing/partial/product.yml"
    prefix: /products
