# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security:loginAction
        _sylius:
            template: SyliusShopBundle::login.html.twig

sylius_shop_login_check:
    path: /login-check
    defaults:
        _controller: sylius.controller.security:checkAction

sylius_shop_logout:
    path: /logout

sylius_shop_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            event: register
            template: SyliusShopBundle::register.html.twig
            redirect:
                route: sylius_shop_account_dashboard
            flash: sylius.customer.register

sylius_shop_request_password_reset_token:
    path: /forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:requestPasswordResetTokenAction
        _sylius:
            template: SyliusShopBundle:Account:requestPasswordReset.html.twig
            redirect: sylius_shop_login

sylius_shop_password_reset:
    path: /forgotten-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.shop_user:resetPasswordAction
        _sylius:
            template: SyliusShopBundle:Account:resetPassword.html.twig
            redirect: sylius_shop_login
