# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_partial_cart_summary:
    path: /summary
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:summaryAction
        _sylius:
            template: $template
            form: Sylius\Bundle\OrderBundle\Form\Type\CartType

sylius_shop_partial_cart_add_item:
    path: /add-item
    methods: [GET]
    defaults:
        _controller: sylius.controller.order_item:addAction
        _sylius:
            template: $template
            factory:
                method: createForProduct
                arguments: [expr:service('sylius.repository.product').find($productId)]
            form:
                type: Sylius\Bundle\CoreBundle\Form\Type\Order\AddToCartType
                options:
                    product: expr:service('sylius.repository.product').find($productId)
