# This file is a part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_partial_cart_item_add:
    path: /add
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.cart_item:addAction
        _sylius:
            factory:
                method: createForProduct
                arguments: [expr:service('sylius.repository.product').find($productId)]
            form:
                type: sylius_cart_item
                options:
                    product: expr:service('sylius.repository.product').find($productId)
            template: $template
            redirect: sylius_shop_cart_summary
