# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_partial_product_association_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_association:showAction
        _sylius:
            template: $template
            repository:
                method: ["expr:service('sylius.repository.product_association')", "findAssociatedProductsWithinChannel"]
                arguments: 
                    - $id
                    - $productId
                    - "expr:service('sylius.context.channel').getChannel()"
