# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_shop_partial_product_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            repository:
                method: findEnabledByTaxonCodeAndChannel
                arguments: [$code, 'expr:service("sylius.context.channel").getChannel()']
            template: SyliusShopBundle:Product:index.html.twig
