sylius_shop_partial_taxon_by_code:
    path: /{code}
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            repository:
                method: findChildrenAsTreeByRootCode
                arguments: [$code]
            template: $template
