sylius_shop_partial_product_latest:
    path: /latest/{count}
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            repository:
                method: findLatestByChannel
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - $count
            template: $template
